#!/bin/sh
# 下载签到助手
cd ${OPENSHIFT_REPO_DIR}
curl -s http://git.oschina.net/kenvix/Tieba-Cloud-Sign/repository/archive?ref=master > Tieba-sign.zip

# 展开
unzip Tieba-sign.zip
cp -r Tieba-Cloud-Sign/* ./
rm -rf Tieba-sign.zip Tieba-Cloud-Sign

#禁止APC缓存
echo 'php_value apc.cache_by_default off' > ${OPENSHIFT_REPO_DIR}.htaccess