#!/bin/sh

# 禁止APC缓存
echo 'php_value apc.cache_by_default off' > ${OPENSHIFT_REPO_DIR}.htaccess

# 下载签到助手
cd ${OPENSHIFT_REPO_DIR}
curl -s https://codeload.github.com/kenvix/Tieba-Cloud-Sign/zip/master > Tieba-sign.zip
unzip Tieba-sign.zip
cp -r Tieba-Cloud-Sign-master/* ./
rm -rf Tieba-sign.zip Tieba-Cloud-Sign-master

# 下载文件管理器
cd ${OPENSHIFT_REPO_DIR}
git clone https://github.com/kalcaddle/KODExplorer filebrowser/